export const STATUS_SUCCESS = 200;
export const STATUS_NORMALERROR = -11;

export const STATUS_SUCCESS_MESSAGE = 20003;
export const STATUS_QUERY_NULL_MESSAGE = 40003;
export const STATUS_QUERY_NULL_NOLOGIN = 405;//未登录

export const STATUS_EXCEPTION_MESSAGE = 50001;